# Generated by Django 5.0 on 2026-02-10 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tareas.tarea', verbose_name='Tarea'),
        ),
    ]
