# Generated by Django 5.0 on 2026-02-16 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estado', 'Cambio de Estado'), ('prioridad', 'Cambio de Prioridad'), ('asignacion', 'Cambio de Responsable'), ('creacion', 'Tarea Creada'), ('edicion', 'Tarea Editada'), ('comentario', 'Comentario Agregado'), ('eliminacion', 'Tarea Eliminada')], max_length=20, verbose_name='Tipo de cambio')),
                ('valor_anterior', models.CharField(blank=True, max_length=200, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Valor nuevo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tareas.tarea', verbose_name='Tarea')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historial de Tareas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
